### ISSUE TITLE
`vagrant up` fails with a VMware vagrant provider

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-lite#229]
The most recently published vagrant box for VMware does not work with current levels of vagrant and the vagrant fusion provider.  Attempts to bring up bosh-lite fail with the following:

```
$ vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Box 'cloudfoundry/bosh-lite' could not be found. Attempting to find and install...
    default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: 388
==> default: Loading metadata for box 'cloudfoundry/bosh-lite'
    default: URL: https://atlas.hashicorp.com/cloudfoundry/bosh-lite
==> default: Adding box 'cloudfoundry/bosh-lite' (v388) for provider: vmware_desktop
    default: Downloading: https://atlas.hashicorp.com/cloudfoundry/boxes/bosh-lite/versions/388/providers/vmware_desktop.box
==> default: Successfully added box 'cloudfoundry/bosh-lite' (v388) for 'vmware_desktop'!
/Users/sykesm/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.1.2/lib/vagrant-vmware-fusion/action_farm.rb:430:in `call': undefined method `metadata' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/sykesm/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.1.2/lib/vagrant-vmware-fusion/action_farm.rb:1236:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/sykesm/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.1.2/lib/vagrant-vmware-fusion/action_farm.rb:99:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/sykesm/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.1.2/lib/vagrant-vmware-fusion/action_farm.rb:273:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/sykesm/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.1.2/lib/vagrant-vmware-fusion/action_farm.rb:160:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:212:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:189:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:176:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:176:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

Versions:

```
$ vmware-vmx -v

VMware Fusion Information:
VMware Fusion 7.1.0 build-2314774 Release
```

```
$ vagrant plugin list | grep vmware
vagrant-vmware-fusion (3.1.2)
```

```
$ vagrant --version
Vagrant 1.7.1
```

**Comment by squeedee** [comment]
I can confirm this bug. Box 387 did not work either.

**Comment by squeedee** [comment]
Using version 6.0.5 of vagrant
Tried both 2.5.2 and 3.2.0 (latest) of the provider plugin

**Comment by xtreme-andrei-dinin** [comment]
There is some peculiarities with how box_version is set on Vagrantfile that cause this. 
I just pushed a fix at c82c939833fd05ad8e7ad93595ece6d2a054f806
@sykesm, @squeedee Please pull and try again

**Comment by squeedee** [comment]
I used the patch before it was pushed, Dmitri shared it with me. It worked thankyou. I'll also retry using the repo tommorow.

**Comment by cppforlife** [comment]
Closing. Reopen if problem still exists.
