### ISSUE TITLE
[aws] Cannot upload releases or stemcells via URL/bosh.io

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-lite#252]
The follow fails for `bosh upload release` and `bosh upload stemcell` for an AWS bosh-lite I just provisioned with vagrant 1.6.5.

```
$ bosh upload release https://bosh.io/d/github.com/concourse/concourse
...
Error 100001: Downloading remote release failed. Check task debug log for details.
```

```
$ bosh task 1 --debug

Director task 1
# Logfile created on 2015-04-14 04:09:18 +0000 by logger.rb/44203
I, [2015-04-14T04:09:18.374262 #1458]  INFO -- : Director Version : 1.2749.0
I, [2015-04-14T04:09:18.374323 #1458]  INFO -- : Enqueuing task: 1
I, [2015-04-14T04:09:18.703735 #1763] [0x3fe3bce7b334]  INFO -- : Looking for task with task id 1
D, [2015-04-14T04:09:18.705209 #1763] [0x3fe3bce7b334] DEBUG -- : (0.000913s) SELECT * FROM "tasks" WHERE "id" = 1
I, [2015-04-14T04:09:18.708003 #1763] [0x3fe3bce7b334]  INFO -- : Starting task: 1
I, [2015-04-14T04:09:18.708105 #1763] [task:1]  INFO -- : Creating job
D, [2015-04-14T04:09:18.708802 #1763] [task:1] DEBUG -- : (0.000187s) SELECT * FROM "tasks" WHERE "id" = 1
I, [2015-04-14T04:09:18.709202 #1763] [task:1]  INFO -- : Performing task: 1
D, [2015-04-14T04:09:18.710363 #1763] [task:1] DEBUG -- : (0.000103s) BEGIN
D, [2015-04-14T04:09:18.712467 #1763] [task:1] DEBUG -- : (0.000462s) UPDATE "tasks" SET "state" = 'processing', "timestamp" = '2015-04-14 04:09:18.709504+0000', "description" = 'create release', "result" = NULL, "output" = '/var/vcap/store/director/tasks/1', "user_id" = NULL, "checkpoint_time" = '2015-04-14 04:09:18.709633+0000', "type" = 'update_release' WHERE ("id" = 1)
D, [2015-04-14T04:09:18.714395 #1763] [task:1] DEBUG -- : (0.001752s) COMMIT
I, [2015-04-14T04:09:18.714550 #1763] [task:1]  INFO -- : Processing update release
I, [2015-04-14T04:09:18.714628 #1763] [task:1]  INFO -- : Downloading remote release
I, [2015-04-14T04:09:18.715119 #1763] [task:1]  INFO -- : Downloading remote release from https://bosh.io/d/github.com/concourse/concourse
E, [2015-04-14T04:09:18.794575 #1763] [task:1] ERROR -- : Downloading remote release from https://bosh.io/d/github.com/concourse/concourse failed: Found
E, [2015-04-14T04:09:18.795835 #1763] [task:1] ERROR -- : Downloading remote release failed. Check task debug log for details.
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/download_helper.rb:25:in `block (2 levels) in download_remote_file'
/var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:1415:in `block (2 levels) in transport_request'
/var/vcap/packages/ruby/lib/ruby/2.1.0/net/http/response.rb:162:in `reading_body'
/var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:1414:in `block in transport_request'
/var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
/var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
/var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:1378:in `request'
/var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:1280:in `request_get'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/download_helper.rb:19:in `block in download_remote_file'
/var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:853:in `start'
/var/vcap/packages/ruby/lib/ruby/2.1.0/net/http.rb:583:in `start'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/download_helper.rb:16:in `download_remote_file'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/jobs/update_release.rb:74:in `download_remote_release'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/jobs/update_release.rb:49:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/jobs/base_job.rb:54:in `block in single_step_stage'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/jobs/base_job.rb:48:in `block in track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/event_log.rb:83:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/event_log.rb:83:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/event_log.rb:36:in `track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/jobs/base_job.rb:46:in `track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/jobs/base_job.rb:54:in `single_step_stage'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/jobs/update_release.rb:49:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/job_runner.rb:104:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/job_runner.rb:31:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.2749.0/lib/common/thread_formatter.rb:46:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/job_runner.rb:31:in `run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:227:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2749.0/bin/bosh-director-worker:84:in `<top (required)>'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `load'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `<main>'
D, [2015-04-14T04:09:18.796302 #1763] [task:1] DEBUG -- : (0.000140s) BEGIN
D, [2015-04-14T04:09:18.797212 #1763] [task:1] DEBUG -- : (0.000338s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2015-04-14 04:09:18.795981+0000', "description" = 'create release', "result" = 'Downloading remote release failed. Check task debug log for details.', "output" = '/var/vcap/store/director/tasks/1', "user_id" = NULL, "checkpoint_time" = '2015-04-14 04:09:18.709633+0000', "type" = 'update_release' WHERE ("id" = 1)
D, [2015-04-14T04:09:18.798793 #1763] [task:1] DEBUG -- : (0.001485s) COMMIT
I, [2015-04-14T04:09:18.799042 #1763] [0x3fe3bce7b334]  INFO -- : Task took 0.090892707 seconds to process.
```

**Comment by cppforlife** [comment]
Your bosh-lite is out of date (uses 2749 Director version) and does not support bosh.io URLs. Please update.

**Comment by drnic** [comment]
I don't understand why `vagrant up --provider=aws` is giving me (consistently) an old bosh. I deployed again and it's still failing.

**Comment by drnic** [comment]
I have latest bosh-lite git repo. I keep getting `ami-4cd75224`

**Comment by drnic** [comment]
I needed to run `vagrant box update --provider=aws` to get latest AMI

**Comment by bosh-ci-push-pull** [comment]
I don't think vagrant is aggressive enough about pulling in updates. Have
you tried running `vagrant box update`?

Also this might be related (possibly another vagrant bug) to where we place
box_version within the Vagrantfile. Try moving it outside.
