### ISSUE TITLE
../bosh-lite/bin/provision_cf fails

### ISSUE THREAD

**Issue by sglebs** [cloudfoundry/bosh-lite#347]
```
bosh target 192.168.50.4 lite
cd ..; git clone https://github.com/cloudfoundry/cf-release ; cd cf-release
../bosh-lite/bin/provision_cf
```

```
...
Submodule path 'src/loggregator/src/github.com/ugorji/go': checked out 'f1f1a805ed361a0e078bb537e4ea78cd37dcf065'
Submodule path 'src/smoke-tests': checked out 'eab961481c905718fe3624d05fd62ae803fbc3c0'
Submodule path 'src/statsd-injector': checked out 'e7152f1b153d9f7a0acc0720378b862278af821b'
Submodule path 'src/uaa-release': checked out '9be621523814a0fe03abb9118f6a6036e4f6345e'
Submodule path 'src/uaa-release/src/uaa': checked out '9b5c13d793ebfe358e26559cedc6b528a557b43f'
+ git clean -ffd
Removing latest-bosh-lite-stemcell-warden.tgz
+ set +x
CF Release has been updated
/Library/Ruby/Gems/2.0.0/gems/bosh_cli-1.3202.0/bin/optionally_run_with_bundler.rb:22:in `write': Permission denied - /Library/Ruby/Gems/2.0.0/gems/bosh_cli-1.3202.0/bin/run_bosh_with_bundler.Gemfile (Errno::EACCES)
	from /Library/Ruby/Gems/2.0.0/gems/bosh_cli-1.3202.0/bin/optionally_run_with_bundler.rb:22:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/bosh_cli-1.3202.0/bin/bosh:3:in `<top (required)>'
	from /usr/bin/bosh:23:in `load'
	from /usr/bin/bosh:23:in `<main>'
/Library/Ruby/Gems/2.0.0/gems/bosh_cli-1.3202.0/bin/optionally_run_with_bundler.rb:22:in `write': Permission denied - /Library/Ruby/Gems/2.0.0/gems/bosh_cli-1.3202.0/bin/run_bosh_with_bundler.Gemfile (Errno::EACCES)
	from /Library/Ruby/Gems/2.0.0/gems/bosh_cli-1.3202.0/bin/optionally_run_with_bundler.rb:22:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/bosh_cli-1.3202.0/bin/bosh:3:in `<top (required)>'
	from /usr/bin/bosh:23:in `load'
	from /usr/bin/bosh:23:in `<main>'
Can only target Bosh Lite Director. Please use 'bosh target' before running this script.
```

I did run bosh target!

**Comment by dpb587-pivotal** [comment]
Those `Permission denied` errors look suspicious and sounds like https://github.com/cloudfoundry/bosh-lite/issues/316#issuecomment-161881325 where it was suggested to try locally removing `BOSH_USE_BUNDLER` from [`scripts/generate-bosh-lite-dev-manifest`](https://github.com/cloudfoundry/cf-release/blob/master/scripts/generate-bosh-lite-dev-manifest). Maybe give that a try?

**Comment by sglebs** [comment]
Yes, I believe the gem install failed due to not enough permissions and I had to sudo it.

**Comment by sglebs** [comment]
I tried that. It failed again:
```
Aborted. Please install spiff by following https://github.com/cloudfoundry-incubator/spiff#installation
Incorrect YAML structure in `/Users/mqm/git/cf-release/bosh-lite/deployments/cf.yml': expected Hash at the root
```
I just installed it, will try yet one more time.

**Comment by fhanik** [comment]
You have to install the `spiff` binary and it has to be available in your path

https://github.com/cloudfoundry-incubator/spiff

**Comment by sglebs** [comment]
```
...
  Started updating job loggregator_trafficcontroller_z1 > loggregator_trafficcontroller_z1/0 (57441685-c2cf-43e3-a897-6fbb581c9969). Done (00:00:15)
  Started updating job router_z1 > router_z1/0 (d14e672c-0d2d-4c91-821a-57eed059c123). Done (00:00:37)

Task 3 done

Started		2016-03-10 01:09:17 UTC
Finished	2016-03-10 01:56:43 UTC
Duration	00:47:26

Deployed `cf-warden' to `Bosh Lite Director'
```

```
(env) Marcio-Marchinis-MacBook-Pro-Silver:bosh-lite mqm$ !3743
cf api --skip-ssl-validation https://api.10.244.0.34.xip.io
Setting api endpoint to https://api.10.244.0.34.xip.io...
FAILED
Server error, status code: 404, error code: 0, message: 
```
Is this the expected behaviour?

**Comment by dpb587-pivotal** [comment]
Is the `domain` property of your deployment manifest configured to be `10.244.0.34.xip.io`?

**Comment by dpb587-pivotal** [comment]
You might also want to try `cf api --skip-ssl-validation https://api.bosh-lite.com` instead - it looks like the domain defaults to bosh-lite.com in the [sample manifest](https://github.com/cloudfoundry/cf-release/blob/9e31b98e104825c136d96a711bec2135f4a6ed33/templates/cf-infrastructure-warden.yml#L29).

**Comment by cppforlife** [comment]
Closing due to inactivity.
