### ISSUE TITLE
uploading stemcell fails with EOF

### ISSUE THREAD

**Issue by pourquoi42** [cloudfoundry/bosh-lite#423]
I am following the tutorial http://mariash.github.io/learn-bosh/#upload_stemcell

When I try to upload the stemcell, I get an error message. Following is the entire conversation. (What seems odd to me at first glance is that the uploading process stops at 96%)

```
gerald@gvm:~/w/learn-bosh-release$ wget --content-disposition https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent
--2017-03-15 13:21:16--  https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent
Resolving bosh.io (bosh.io)... 104.25.22.109, 104.25.21.109, 2400:cb00:2048:1::6819:166d, ...
Connecting to bosh.io (bosh.io)|104.25.22.109|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://s3.amazonaws.com/bosh-core-stemcells/warden/bosh-stemcell-3363.12-warden-boshlite-ubuntu-trusty-go_agent.tgz [following]
--2017-03-15 13:21:17--  https://s3.amazonaws.com/bosh-core-stemcells/warden/bosh-stemcell-3363.12-warden-boshlite-ubuntu-trusty-go_agent.tgz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.64.251
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.64.251|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 381333944 (364M) [application/x-tar]
Saving to: ‘bosh-stemcell-3363.12-warden-boshlite-ubuntu-trusty-go_agent.tgz’

bosh-stemcell-3363.12-ward 100%[=======================================>] 363,67M  3,12MB/s    in 2m 26s  

2017-03-15 13:23:44 (2,50 MB/s) - ‘bosh-stemcell-3363.12-warden-boshlite-ubuntu-trusty-go_agent.tgz’ saved [381333944/381333944]


gerald@gvm:~/w/learn-bosh-release$ bosh upload stemcell bosh-stemcell-3363.12-warden-boshlite-ubuntu-trusty-go_agent.tgz 
Acting as user 'admin' on 'Bosh Lite Director'

Verifying stemcell...
File exists and readable                                     OK
Verifying tarball...
Read tarball                                                 OK
Manifest exists                                              OK
Stemcell image file                                          OK
Stemcell properties                                          OK

Stemcell info
-------------
Name:    bosh-warden-boshlite-ubuntu-trusty-go_agent
Version: 3363.12

Checking if stemcell already exists...
No

Uploading stemcell...

bosh-stemcell:  96% |oooooooooooooooooooooooooooooooooooooooooooooooo   | 349.1MB  16.7MB/s ETA:  00:00:00
Director task 70
  Started update stemcell
  Started update stemcell > Extracting stemcell archive. Failed: Extracting stemcell archive failed. Check task debug log for details. (00:00:11)

Error 50000: Extracting stemcell archive failed. Check task debug log for details.

Task 70 error
bosh-stemcell:  96% |oooooooooooooooooooooooooooooooooooooooooooooooo   | 349.9MB  10.2MB/s Time: 00:00:34

For a more detailed error report, run: bosh task 70 --debug
gerald@gvm:~/w/learn-bosh-release$ 
gerald@gvm:~/w/learn-bosh-release$ bosh task 70 --debug
Acting as user 'admin' on 'Bosh Lite Director'

Director task 70
I, [2017-03-15T12:29:01.134268 #1640] [0x2aac5a22f110]  INFO -- TaskHelper: Director Version: 260.0.0
I, [2017-03-15T12:29:01.134355 #1640] [0x2aac5a22f110]  INFO -- TaskHelper: Enqueuing task: 70
I, [2017-03-15 12:29:01 #2628] []  INFO -- DirectorJobRunner: Looking for task with task id 70
D, [2017-03-15 12:29:01 #2628] [] DEBUG -- DirectorJobRunner: (0.001027s) SELECT NULL
D, [2017-03-15 12:29:01 #2628] [] DEBUG -- DirectorJobRunner: (0.003347s) SELECT * FROM "tasks" WHERE "id" = 70
I, [2017-03-15 12:29:01 #2628] []  INFO -- DirectorJobRunner: Found task #<Bosh::Director::Models::Task @values={:id=>70, :state=>"queued", :timestamp=>2017-03-15 12:29:01 UTC, :description=>"create stemcell", :result=>nil, :output=>"/var/vcap/store/director/tasks/70", :checkpoint_time=>2017-03-15 12:29:01 UTC, :type=>"update_stemcell", :username=>"admin", :deployment_name=>nil, :started_at=>nil}>
I, [2017-03-15 12:29:01 #2628] []  INFO -- DirectorJobRunner: Starting task: 70
I, [2017-03-15 12:29:01 #2628] [task:70]  INFO -- DirectorJobRunner: Creating job
D, [2017-03-15 12:29:01 #2628] [task:70] DEBUG -- DirectorJobRunner: (0.000418s) SELECT NULL
D, [2017-03-15 12:29:01 #2628] [task:70] DEBUG -- DirectorJobRunner: (0.000541s) SELECT * FROM "tasks" WHERE "id" = 70
D, [2017-03-15 12:29:01 #2628] [task:70] DEBUG -- DirectorJobRunner: (0.000334s) SELECT NULL
D, [2017-03-15 12:29:01 #2628] [task:70] DEBUG -- DirectorJobRunner: (0.000406s) SELECT * FROM "tasks" WHERE "id" = 70
I, [2017-03-15 12:29:01 #2628] [task:70]  INFO -- DirectorJobRunner: Performing task: #<Bosh::Director::Models::Task @values={:id=>70, :state=>"queued", :timestamp=>2017-03-15 12:29:01 UTC, :description=>"create stemcell", :result=>nil, :output=>"/var/vcap/store/director/tasks/70", :checkpoint_time=>2017-03-15 12:29:01 UTC, :type=>"update_stemcell", :username=>"admin", :deployment_name=>nil, :started_at=>nil}>
D, [2017-03-15 12:29:01 #2628] [task:70] DEBUG -- DirectorJobRunner: (0.003214s) SELECT NULL
D, [2017-03-15 12:29:01 #2628] [task:70] DEBUG -- DirectorJobRunner: (0.000216s) BEGIN
D, [2017-03-15 12:29:01 #2628] [task:70] DEBUG -- DirectorJobRunner: (0.001117s) UPDATE "tasks" SET "state" = 'processing', "timestamp" = '2017-03-15 12:29:01.830326+0000', "description" = 'create stemcell', "result" = NULL, "output" = '/var/vcap/store/director/tasks/70', "checkpoint_time" = '2017-03-15 12:29:01.830687+0000', "type" = 'update_stemcell', "username" = 'admin', "deployment_name" = NULL, "started_at" = '2017-03-15 12:29:01.830568+0000' WHERE ("id" = 70)
D, [2017-03-15 12:29:01 #2628] [task:70] DEBUG -- DirectorJobRunner: (0.005230s) COMMIT
I, [2017-03-15 12:29:01 #2628] [task:70]  INFO -- DirectorJobRunner: Processing update stemcell
I, [2017-03-15 12:29:01 #2628] [task:70]  INFO -- DirectorJobRunner: Update stemcell
I, [2017-03-15 12:29:01 #2628] [task:70]  INFO -- DirectorJobRunner: Extracting stemcell archive
E, [2017-03-15 12:29:12 #2628] [task:70] ERROR -- DirectorJobRunner: Extracting stemcell archive failed in dir /var/vcap/data/tmp/director/stemcell20170315-2628-inn9wu, tar returned 2, output: tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

E, [2017-03-15 12:29:13 #2628] [task:70] ERROR -- DirectorJobRunner: Extracting stemcell archive failed. Check task debug log for details.
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/update_stemcell.rb:56:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/base_job.rb:56:in `block in track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/base_job.rb:54:in `track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/update_stemcell.rb:50:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/job_runner.rb:106:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/job_runner.rb:32:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/job_runner.rb:32:in `run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/db_job.rb:32:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/jobs/db_job.rb:80:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:1046:in `block in spawn_threadpool'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2017-03-15 12:29:13 #2628] [task:70] DEBUG -- DirectorJobRunner: (0.000648s) SELECT NULL
D, [2017-03-15 12:29:13 #2628] [task:70] DEBUG -- DirectorJobRunner: (0.000184s) BEGIN
D, [2017-03-15 12:29:13 #2628] [task:70] DEBUG -- DirectorJobRunner: (0.000596s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2017-03-15 12:29:13.497443+0000', "description" = 'create stemcell', "result" = 'Extracting stemcell archive failed. Check task debug log for details.', "output" = '/var/vcap/store/director/tasks/70', "checkpoint_time" = '2017-03-15 12:29:01.830687+0000', "type" = 'update_stemcell', "username" = 'admin', "deployment_name" = NULL, "started_at" = '2017-03-15 12:29:01.830568+0000' WHERE ("id" = 70)
D, [2017-03-15 12:29:13 #2628] [task:70] DEBUG -- DirectorJobRunner: (0.002244s) COMMIT
I, [2017-03-15 12:29:13 #2628] []  INFO -- DirectorJobRunner: Task took 11.685310557 seconds to process.

Task 70 error
gerald@gvm:~/w/learn-bosh-release$ 
```

**Comment by dpb587-pivotal** [comment]
You might want to double check the integrity of the downloaded stemcell. The digest can be found from http://bosh.io/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent and for 3363.12 should be `a72b63c5b17ab2fd8e9e92c4a5019298765d8dc1`.

You can also double check you have enough disk space (both on the vm via `vagrant ssh` and on the host).

Another suggestion would be running `vagrant reload`, particularly if you have moved the bosh-lite directory after doing the initial `vagrant up` (see [#109](https://github.com/cloudfoundry/bosh-lite/issues/109#issuecomment-157324215)).

**Comment by pourquoi42** [comment]
Thanks for your help. I followed your suggestion to narrow down the problem. Checksum is ok. vagrant reload didnt change anything. For the diskspace, I am not sure. While there is plenty of space in general, there is limited space under /var/vcap/data/sys/run . Can that be the problem? How to increase that space if that may be the issue?

```
vagrant@agent-id-bosh-0:~$ df -h
Filesystem                   Size  Used Avail Use% Mounted on
udev                         2.9G  4.0K  2.9G   1% /dev
tmpfs                        597M  1.4M  596M   1% /run
/dev/mapper/ubuntu--vg-root   78G  2.9G   71G   4% /
none                         4.0K     0  4.0K   0% /sys/fs/cgroup
none                         5.0M     0  5.0M   0% /run/lock
none                         3.0G     0  3.0G   0% /run/shm
none                         100M     0  100M   0% /run/user
/dev/sda1                    236M   82M  142M  37% /boot
tmpfs                        1.0M   52K  972K   6% /var/vcap/data/sys/run
vagrant                       35G   15G   20G  44% /vagrant
cgroup                       3.0G     0  3.0G   0% /tmp/garden-/cgroup

```

**Comment by dpb587-pivotal** [comment]
That's odd. Try recreating the vagrant VM from scratch `vagrant destroy && vagrant up` just to be sure everything is in a clean state. Also, make sure you're running recent versions of  You could also try manually extracting the stemcell on the vagrant vm with `tar -xzf stemcell-file.tgz` and see if it fails (if so, you may be able to enable verbose mode; it'd be weird for it to fail though since checksum matches).

Tried locally and it seems to work...

```
$ wget --content-disposition https://s3.amazonaws.com/bosh-core-stemcells/warden/bosh-stemcell-3363.12-warden-boshlite-ubuntu-trusty-go_agent.tgz
$ BOSH_CLIENT=admin BOSH_CLIENT_SECRET=admin gobosh -e https://192.168.50.4:25555 --ca-cert ca/certs/ca.crt us bosh-stemcell-3363.12-warden-boshlite-ubuntu-trusty-go_agent.tgz
Using environment 'https://192.168.50.4:25555' as client 'admin'

######################################################### 100.00% 142.37 MB/s 2s
Task 1

23:36:45 | Update stemcell: Extracting stemcell archive (00:00:02)
23:36:47 | Update stemcell: Verifying stemcell manifest (00:00:00)
23:36:47 | Update stemcell: Checking if this stemcell already exists (00:00:00)
23:36:47 | Update stemcell: Uploading stemcell bosh-warden-boshlite-ubuntu-trusty-go_agent/3363.12 to the cloud (00:00:12)
23:36:59 | Update stemcell: Save stemcell bosh-warden-boshlite-ubuntu-trusty-go_agent/3363.12 (28bbbe8a-3124-49b4-57f0-c374ae0a9d7e) (00:00:00)

Started  Fri Mar 17 23:36:45 UTC 2017
Finished Fri Mar 17 23:36:59 UTC 2017
Duration 00:00:14

Task 1 done

Succeeded
```

**Comment by pourquoi42** [comment]
vagrant destroy / up didn't help but I could get it to work after lowering the number of cpus in the virtualbox ! My Vagrantfile now looks like (the line with ### is added):

```
config.vm.provider :virtualbox do |v, override|
    override.vm.box_version = '9000.137.0' # ci:replace
    v.cpus = 1 ###
  end
```

After that, the bosh upload works. Can there be some kind of racecondition? untgz-ing starting before the upload is finalized ?

**Comment by dpb587-pivotal** [comment]
Not sure why CPUs would be affecting things, but that makes me think your host may simply be underpowered. If running on a cloud workstation, perhaps try scaling to something more powerful.

From the code side, ruby isn't invoked until the stemcell upload was fully written to disk, so I can't think of a race condition like that.

Do you see any difference if doing `bosh upload-stemcell https://s3.amazonaws.com/bosh-core-stemcells/warden/bosh-stemcell-3363.12-warden-boshlite-ubuntu-trusty-go_agent.tgz` as opposed to uploading a local file?

**Comment by pourquoi42** [comment]
I can't follow up further on this issue. My suspicion is there is something odd and very specific to my setup. Closing therefore.
