### ISSUE TITLE
Error 450001: Action Failed get_task: Task xxx result: Updating certificates with retries

### ISSUE THREAD

**Issue by ivandavidov** [cloudfoundry/bosh-lite#429]
As suggested in [this issue](https://github.com/cloudfoundry/cf-release/issues/1199), I'm cloning my issue on the bosh-lite repo.

===   ===   ===

This is the error which I get when I execute ``bosh deploy`` on my local bosh-lite:

```
Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 14
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Done (00:00:15)

  Started preparing package compilation > Finding packages to compile. Done (00:00:04)

  Started creating missing vms
  Started creating missing vms > consul_z1/b33533ae-5ee4-41c3-bd55-f2e63b1264c5 (0)
  Started creating missing vms > nats_z1/7b4f7d5d-ea16-4919-9aca-c8f10ba92a2b (0)
  Started creating missing vms > etcd_z1/e8c0989b-92b7-41eb-a926-f2b78cb9d9f4 (0)
  Started creating missing vms > blobstore_z1/2e4206e4-509b-4ed5-ab2b-f2a5db46b876 (0)
  Started creating missing vms > postgres_z1/1d3d2988-7b27-4d8b-ae56-53a5a69c0f87 (0)
  Started creating missing vms > uaa_z1/ea9a3f00-8109-41a5-8ef4-e092df1e29f4 (0)
  Started creating missing vms > api_z1/e058123d-220a-4f70-bd64-6dae956dccec (0)
  Started creating missing vms > runner_z1/66ee4603-01fb-40d5-93c2-5274c8602a64 (0)
  Started creating missing vms > hm9000_z1/c62bf24e-f614-4741-9a18-d28ede960d13 (0)
  Started creating missing vms > doppler_z1/bafae16f-b6b3-49c1-a926-b27db8864073 (0)
  Started creating missing vms > loggregator_trafficcontroller_z1/1c9866ee-45cf-4af6-92c3-20aa4bd59480 (0)
  Started creating missing vms > router_z1/6b05b4fe-1579-4806-ad95-a1a61760bb04 (0)
  Started creating missing vms > ha_proxy_z1/05967303-16a7-4c29-b65e-a54cd79a4bb5 (0)
   Failed creating missing vms > runner_z1/66ee4603-01fb-40d5-93c2-5274c8602a64 (0): Action Failed get_task: Task c8f3bfb0-5b26-4c03-7cf4-d9031e20c571 result: Updating certificates with retries (00:03:38)
   Failed creating missing vms > nats_z1/7b4f7d5d-ea16-4919-9aca-c8f10ba92a2b (0): Action Failed get_task: Task 955aee33-6ff9-4f7c-6c85-8a4461e8978f result: Updating certificates with retries (00:03:39)
   Failed creating missing vms > etcd_z1/e8c0989b-92b7-41eb-a926-f2b78cb9d9f4 (0): Action Failed get_task: Task e8615236-e9e5-47b8-5157-e10a0321e796 result: Updating certificates with retries (00:03:46)
   Failed creating missing vms > postgres_z1/1d3d2988-7b27-4d8b-ae56-53a5a69c0f87 (0): Action Failed get_task: Task e4f71608-fab1-479c-7e7d-efdd569e4a5b result: Updating certificates with retries (00:03:52)
   Failed creating missing vms > consul_z1/b33533ae-5ee4-41c3-bd55-f2e63b1264c5 (0): Action Failed get_task: Task e268558a-d5b5-4d97-708c-28dffafde19d result: Updating certificates with retries (00:03:54)
   Failed creating missing vms > ha_proxy_z1/05967303-16a7-4c29-b65e-a54cd79a4bb5 (0): Action Failed get_task: Task 93dbbf57-2fec-42f5-5dad-4047946e7a76 result: Updating certificates with retries (00:04:02)
   Failed creating missing vms > api_z1/e058123d-220a-4f70-bd64-6dae956dccec (0): Action Failed get_task: Task 093eab12-e152-42cc-7f50-1f0719a9db50 result: Updating certificates with retries (00:04:06)
   Failed creating missing vms > router_z1/6b05b4fe-1579-4806-ad95-a1a61760bb04 (0): Action Failed get_task: Task 5376cf25-7605-4054-7586-0e353b779160 result: Updating certificates with retries (00:04:07)
   Failed creating missing vms > hm9000_z1/c62bf24e-f614-4741-9a18-d28ede960d13 (0): Action Failed get_task: Task 2fb8d128-98f1-4a7f-4d01-171ffa984411 result: Updating certificates with retries (00:04:08)
   Failed creating missing vms > uaa_z1/ea9a3f00-8109-41a5-8ef4-e092df1e29f4 (0): Action Failed get_task: Task 7d0ac8b4-feb8-4468-7c6a-423c054d6614 result: Updating certificates with retries (00:04:09)
   Failed creating missing vms > loggregator_trafficcontroller_z1/1c9866ee-45cf-4af6-92c3-20aa4bd59480 (0): Action Failed get_task: Task b7fce106-3e84-4c41-618e-c05b36635d3c result: Updating certificates with retries (00:04:10)
   Failed creating missing vms > doppler_z1/bafae16f-b6b3-49c1-a926-b27db8864073 (0): Action Failed get_task: Task 626848b5-d115-42f2-7a02-db2aa65f253a result: Updating certificates with retries (00:04:10)
   Failed creating missing vms > blobstore_z1/2e4206e4-509b-4ed5-ab2b-f2a5db46b876 (0): Action Failed get_task: Task 38cbcc17-8a88-453a-7047-66272c8007b4 result: Updating certificates with retries (00:04:11)
   Failed creating missing vms (00:04:11)

Error 450001: Action Failed get_task: Task c8f3bfb0-5b26-4c03-7cf4-d9031e20c571 result: Updating certificates with retries

Task 14 error

For a more detailed error report, run: bosh task 14 --debug
```

After some research I am pretty sure this is due to yet another timeout which I experience on my not-so-great hardware. I believe this is the original code which throws this error:

https://github.com/cloudfoundry/bosh-agent/blob/master/platform/cert/cert_manager.go

On line 141 we have this:

```
return bosherr.Error("Updating certificates with retries")
```
I was able to resolve my previous timeout issues by significantly reducing the load on my laptop and rebooting my Ubuntu OS in pure console mode. At this point I believe I have no other options to squeeze any more performance from my machine, so I'll be happy if you could assist me with advice on how to proceed. All I'm trying to do is to deploy cf-release 258 on bosh-lite. That's all I want to achieve. :)

Regards,
Ivan Davidov

**Comment by dpb587-pivotal** [comment]
This definitely seems like an issue with having an underpowered host machine. Unfortunately, there's not an easy workaround for this particular error, and the timeout for this is not configurable. I'd recommend testing out on the cloud if you continue seeing these sorts of things.

If you're willing to spend the extra time, you could try colocating most/all the jobs onto a single VM in your deployment manifest to reduce the load. Other generic recommendations are to make sure few other things are running which may be stealing CPU.

**Comment by ivandavidov** [comment]
> If you're willing to spend the extra time, you could try colocating most/all the jobs onto a single VM in your deployment manifest to reduce the load.

This seems like an interesting task. I'll focus on that for now. I'm going to close this issue since it seems it is not really an issue with CF/bosh-lite and I got some really useful hints.

I'm really glad you guys pay attention to the community! Thank you!

**Comment by deltatree** [comment]
I have also this issue - and my machine has 24 cores and 1024 gb ram. The load of the vm containing bosh-lite is high - very high - I found the reason: dns lookups are not possible and this is causing loops of all daemons... If I solve the dns issue: doppler is not reachable (it cannot be started: Updating certificates with retries...) -> doppler not reachable is causing loops of all daemons - high load ...
You see my dilemma?!

**Comment by ivandavidov** [comment]
I'm reopening the issue due to @deltatree's comment.

**Comment by dpb587-pivotal** [comment]
@deltatree the updating certificates step should be happening very early in the configuration process (before dns is needed). Can you provide the error messages or stacktraces you're seeing?

**Comment by Niranjana-5588** [comment]
I got this issue as well

```
D, [2017-07-16 16:42:00 #31381] [task:14] DEBUG -- DirectorJobRunner: (0.000935s) COMMIT
E, [2017-07-16 16:42:00 #31381] [task:14] ERROR -- DirectorJobRunner: Action Failed get_task: Task ed4b402d-67e7-4f03-7ff1-f73a323b4e10 result: Updating certificates with retries
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/agent_client.rb:247:in `handle_method'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/agent_client.rb:302:in `handle_message_with_retry'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/agent_client.rb:55:in `method_missing'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/agent_client.rb:357:in `get_task_status'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/agent_client.rb:166:in `wait_for_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/agent_client.rb:321:in `send_message'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/agent_client.rb:120:in `update_settings'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/instance.rb:191:in `update_instance_settings'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/vm_creator.rb:78:in `create_for_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:144:in `create_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:185:in `instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:16:in `with_reused_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:115:in `prepare_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:66:in `block in compile_package'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/lock_helper.rb:48:in `block in with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/lock.rb:53:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/lock_helper.rb:48:in `with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:59:in `compile_package'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:204:in `block (2 levels) in process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:202:in `block in process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:198:in `process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:162:in `block (4 levels) in compile_packages'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2017-07-16 16:42:00 #31381] [task:14] DEBUG -- DirectorJobRunner: (0.000138s) SELECT NULL
D, [2017-07-16 16:42:00 #31381] [task:14] DEBUG -- DirectorJobRunner: (0.000086s) BEGIN
D, [2017-07-16 16:42:00 #31381] [task:14] DEBUG -- DirectorJobRunner: (0.000321s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2017-07-16 16:42:00.006889+0000', "description" = 'create deployment', "result" = 'Action Failed get_task: Task ed4b402d-67e7-4f03-7ff1-f73a323b4e10 result: Updating certificates with retries', "output" = '/var/vcap/store/director/tasks/14', "checkpoint_time" = '2017-07-16 16:24:43.689421+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'cf-warden', "started_at" = '2017-07-16 16:24:43.689333+0000' WHERE ("id" = 14)
D, [2017-07-16 16:42:00 #31381] [task:14] DEBUG -- DirectorJobRunner: (0.001215s) COMMIT
I, [2017-07-16 16:42:00 #31381] []  INFO -- DirectorJobRunner: Task took 17 minutes 16.323396159999902 seconds to process.

```
How to fix this ?

**Comment by edwardstudy** [comment]
We got this issue of director worker:
```
* Process memory map:

/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:321: [BUG] rb_vm_get_cref: unreachable
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0002 p:0007 s:0005 e:000004 BLOCK  /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:321 [FINISH]
c:0001 p:---- s:0002 e:000001 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:321:in `block in create_with_logging_context'

-- C level backtrace information -------------------------------------------
[BUG] Segmentation fault at 0x00000000000000
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

-- Machine register context ------------------------------------------------
 RIP: 0x00005623ac5cc5a5 RBP: 0x00007f0ce7545d88 RSP: 0x00007f0ce7545d88
 RAX: 0x0000000000000000 RBX: 0x00007f0ce7545ef0 RCX: 0x00007f0ced602c5a
 RDX: 0x0000000000008000 RDI: 0x00005623b055b120 RSI: 0x00007f0ce7545d70
  R8: 0x0000000000000000  R9: 0x0000000000000000 R10: 0x0000000000000d70
 R11: 0x0000000000000246 R12: 0x0000000000000000 R13: 0x00007fff7bfe818f
 R14: 0x0000000000100000 R15: 0x00005623b0b5cac0 EFL: 0x0000000000010246

-- C level backtrace information -------------------------------------------
[BUG] Segmentation fault at 0x00000000000000
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0001 p:---- s:0002 e:000001 (none) [FINISH]


-- Machine register context ------------------------------------------------
 RIP: 0x000055a91fe675a5 RBP: 0x00007f782bcf1d88 RSP: 0x00007f782bcf1d88
 RAX: 0x0000000000000000 RBX: 0x00007f782bcf1ef0 RCX: 0x00007f7831daec5a
 RDX: 0x0000000000008000 RDI: 0x000055a922cebf60 RSI: 0x00007f782bcf1d70
  R8: 0x0000000000000000  R9: 0x000000000000fef0 R10: 0x0000000000000d70
 R11: 0x0000000000000246 R12: 0x0000000000000000 R13: 0x00007fff1a959ecf
 R14: 0x0000000000100000 R15: 0x000055a923d847f0 EFL: 0x0000000000010246

-- C level backtrace information -------------------------------------------
```

**Comment by dpb587-pivotal** [comment]
Closing - bosh-lite is no longer supported, director/v260 is old, and we're no longer using ruby/v2.3; please use [cloudfoundry/bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) for development and testing instead.

**Comment by forexamplelyr** [comment]
@dpb587-pivotal I will be so appreciate if you can take your time to answer my question：）
my machine's configuration is 4 cpu， 20G RAM， 100G disk
